pokemon_project/pokemon/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.email_pokemon, name='email_pokemon')
]

pokemon_project/pokemon_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pokemon.urls')),
]

pokemon_project/pokemon/models.py
from django.db import models

class Pokemon(models.Model):
    name = models.CharField(max_length=255)

class Ability(models.Model):
    name = models.CharField(max_length=255)
    pokemon = models.ForeignKey(Pokemon, on_delete=models.CASCADE)

pokemon_project/pokemon/forms.py
from django import forms

class PokemonForm(forms.Form):
    email = forms.CharField(
        label='Email (separate multiple addresses with spaces):',
        widget=forms.Textarea(attrs={'placeholder': 'Enter Email Addresses'}),
        required=True
    )
    pokemon_name = forms.CharField(
        label='Pokemon (separate multiple addresses with spaces):',
        widget=forms.Textarea(attrs={'placeholder': 'Enter Pokemon Name'}),
        required=True
    )

pokemon_project/pokemon/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .forms import PokemonForm
from .util import *
from .pokemonUtil import *
from django.core.exceptions import ValidationError
import os

def email_pokemon(request):
    if request.method == 'POST':
        form = PokemonForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            email_addresses = email.split()
            temp = form.cleaned_data['pokemon_name']
            pokemon_names = temp.split()

            success_messages = []
            failure_messages = []
            pdf_filenames = []

            for email_address in email_addresses:
                if not is_valid_email(email_address):
                    failure_messages.append(f"Invalid email address: {email_address}")
                    continue

            if failure_messages:
                return JsonResponse({'message': '\n'.join(failure_messages), 'success': False}, status=400)

            for pokemon_name in pokemon_names:
                data = retrieve_pokemon_data(pokemon_name)

                if data:
                    abilities = get_pokemon_abilities(data)
                    pdf_filename = create_pdf(pokemon_name, abilities)
                    pdf_filenames.append(pdf_filename)
                    success_messages.append(f"Abilities for {pokemon_name} are ready.")
                else:
                    failure_messages.append(f"Failed to retrieve data for {pokemon_name}")
            
            if failure_messages:        
                return JsonResponse({'message': '\n'.join(failure_messages), 'success': False}, status=400)
            merged_pdf_filename = merge_pdfs(pdf_filenames)

            if not merged_pdf_filename:
                return JsonResponse({'message': 'Failed to merge PDF files', 'success': False}, status=400)
            
            if len(pokemon_names) == 1:
                send_email_with_pdfs(pdf_filenames, email_addresses)
            else:
                send_email_with_pdfs(pdf_filenames + [merged_pdf_filename], email_addresses)

            for pdf_filename in pdf_filenames:
                os.remove(pdf_filename)

            os.remove(merged_pdf_filename)

            return JsonResponse({'message': 'Email sent successfully', 'success': True})
        else:
            return JsonResponse({'message': 'Form data is invalid', 'success': False}, status=400)
    else:
        form = PokemonForm()
        return render(request, 'pokemon/email_pokemon.html', {'form': form})

pokemon_project/pokemon/templates/pokemon/email_pokemon.html
<!DOCTYPE html>
<html>
  <head>
    <title>Email Pokemon Form</title>

    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css"
    />
    <style>
      .success-message {
        margin-top: 20px;
        padding: 10px;
        background-color: #d4edda;
        border: 1px solid #c3e6cb;
        border-radius: 4px;
      }
      .failed-message {
        margin-top: 20px;
        padding: 10px;
        background-color: #FF0000;
        border: 1px solid #c3e6cb;
        border-radius: 4px;
      }
      .button-container {
        display: flex;
        align-items: center;
      }
      .query-button {
        margin-left: 10px; /* Add margin to the left of the button */
      }
    </style>
  </head>
  <body>
    <div class="container mt-4">
      <h1>Email a Pokemon's Abilities</h1>

      <div id="successMessage" class="success-message" style="display: none;">
        Email sent successfully!
      </div>

      <div id="failSendMessage" class="failed-message" style="display: none;">
        Fail!
      </div>

      <div id="pokefail" class="failed-message" style="display: none;">
        Couldn't find pokemon
      </div>

        <div class="mb-3">
          <label for="id_email" class="form-label">Email (separate multiple addresses with spaces):</label>
          <textarea
            class="form-control"
            id="id_email"
            name="email"
            placeholder="Enter Email Addresses"
            required
          ></textarea>
        </div>
        

        <div class="mb-3">
          <label for="id_email" class="form-label">Pokemon: (separate multiple addresses with spaces)</label>
          <div class="button-container">
            <textarea
              type="text"
              class="form-control"
              id="id_pokemon_name"
              name="pokemon_name"
              placeholder="Enter Pokemon Name"
              required
            ></textarea>

            <button class="btn btn-primary query-button" id="queryButton">
              Query
            </button>
          </div>
        </div>

        <button class="btn btn-primary" id="sendEmailButton">Send Email</button>

      <div id="abilitiesTable"></div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <script>
      document.getElementById("queryButton").addEventListener("click", (event) => {
        event.preventDefault();
    
        const pokemonNames = document.getElementById("id_pokemon_name").value.split(/\s+/);
        const abilitiesTable = document.getElementById("abilitiesTable");

        function hideMessages() {
          $("#successMessage, #failSendMessage, #pokefail").fadeOut();
        }

        function fetchAllPokemonAbilities(pokemonNames) {
          abilitiesTable.innerHTML = '';
        
          pokemonNames.forEach((pokemonName) => {
            const apiUrl = `https://pokeapi.co/api/v2/pokemon/${pokemonName.toLowerCase()}`;
            fetch(apiUrl)
              .then((response) => response.json())
              .then((data) => {
                const abilities = data.abilities;
                const abilityDescriptions = [];
        
                if (abilities.length === 0) {
                  $("#pokefail").fadeIn();
                  setTimeout(hideMessages, 2000);
                  abilitiesTable.innerHTML += failMessage;
                  return;
                }
        
                function fetchAbilityDescription(url, index) {
                  fetch(url)
                    .then((response) => response.json())
                    .then((abilityData) => {
                      const effectEntry = abilityData.effect_entries.find(
                        (entry) => entry.language.name === "en"
                      );
                      if (effectEntry) {
                        abilityDescriptions[index] = effectEntry.short_effect;
                      } else {
                        abilityDescriptions[index] = "No description available";
                      }
        
                      if (abilityDescriptions.length === abilities.length) {
                        const tableHTML = `<table class="table">
                            <thead>
                                <tr>
                                    <th>Pokemon Name</th>
                                    <th>Ability Name</th>
                                    <th>Description</th>
                                </tr>
                            </thead>
                            <tbody>
                                ${abilities
                                  .map((ability, index) =>
                                    `<tr><td>${pokemonName}</td><td>${ability.ability.name}</td><td>${abilityDescriptions[index]}</td></tr>`
                                  )
                                  .join("")}
                            </tbody>
                        </table>`;
                        abilitiesTable.innerHTML += tableHTML;
                      }
                    })
                    .catch((error) => {
                      console.error(error);
                      $("#pokefail").fadeIn();
                      setTimeout(hideMessages, 2000);
                    });
                }
        
                abilities.forEach((ability, index) => {
                  fetchAbilityDescription(ability.ability.url, index);
                });
              })
              .catch((error) => {
                console.error(error);
                $("#pokefail").fadeIn();
                setTimeout(hideMessages, 2000);
              });
          });
        }
    
        fetchAllPokemonAbilities(pokemonNames);
      });
    </script>    
    
    <script>
      function getCookie(name) {
        var value = "; " + document.cookie;
        var parts = value.split("; " + name + "=");
        if (parts.length === 2) return parts.pop().split(";").shift();
      }
      function hideMessages() {
        $("#successMessage, #failSendMessage").fadeOut();
      }
      document.getElementById("sendEmailButton").addEventListener("click", (event) => {
        event.preventDefault();
      
        const email = document.getElementById("id_email").value;
        const pokemonName = document.getElementById("id_pokemon_name").value;
      
        $.ajax({
          url: '',
          type: 'POST',
          headers: {
            'X-CSRFToken': getCookie("csrftoken"),
          },
          data: {
            email: email,
            pokemon_name: pokemonName,
          },
          success: function(data) {
            if (data.success) {
              $("#successMessage").fadeIn();
            } 
            else {
              console.error('Email sending failed');
              if (data.message === 'Form data is invalid') {
                $("#failSendMessage").fadeIn();
              } else {
                $("#failSendMessage").fadeIn();
              }
            }
            setTimeout(hideMessages, 2000);
          },
          error: function() {
            console.error('Error sending email');
            $("#failSendMessage").fadeIn();
            setTimeout(hideMessages, 2000);
          },
        });
      });
    </script>
  </body>
</html>